### ISSUE TITLE
Get Streamlabs Access?

### ISSUE THREAD

**Issue by jontstaz** [Loukious/StreamLabsTikTokStreamKeyGenerator#1]
Hi,

How can I get access via the TikTok application link? It wants me to fill in a link to my live stream on another platform and screenshots to prove account ownership/viewer numbers, etc. I don't stream anywhere else, I just want tiktok live OBS access. Is there anyway to get it without having to fill in that application that requires me to already be streaming elsewhere?

Thanks,

**Comment by Loukious** [comment]
> Hi,
> 
> How can I get access via the TikTok application link? It wants me to fill in a link to my live stream on another platform and screenshots to prove account ownership/viewer numbers, etc. I don't stream anywhere else, I just want tiktok live OBS access. Is there anyway to get it without having to fill in that application that requires me to already be streaming elsewhere?
> 
> Thanks,

Try creating a twitch account then go [here](https://dashboard.twitch.tv/u/loukioustn/home) and take a screenshot. For the concurrent viewers put 10. They don't seem to verify the concurrent viewers nor do they care about how many followers you have. A friend of mine got access with just 99 followers on twitch.
