### ISSUE TITLE
damaged or incomplete

### ISSUE THREAD

**Issue by keepingita1** [Loukious/StreamLabsTikTokStreamKeyGenerator#10]
![tempImageJYuC6f](https://github.com/user-attachments/assets/7aad235a-5ea8-4e4b-bad1-e2b7ff8af64e)

**Comment by Loukious** [comment]
Does this version work for you? https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v0.0.4

**Comment by keepingita1** [comment]
Yes, I tried every version. None of them work for me.

**Comment by Loukious** [comment]
Then it's probably have something to do with your MacOS version. I have no way to verify it. Run the Python script instead.

**Comment by Loukious** [comment]
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/issues/9
