### ISSUE TITLE
key generator with virus 

### ISSUE THREAD

**Issue by JulioGomez11** [Loukious/StreamLabsTikTokStreamKeyGenerator#14]
I have the problem that when I start the key generator script, the system detects that it has a corrupt file or virus that prevents it from functioning correctly. A few hours ago, I was testing it and it worked, plus I did multistream. This surprises me. Is there any solution? This problem appeared on the date and time of this post. I would greatly appreciate your help.
![Imagen de WhatsApp 2024-08-18 a las 15 30 57_be8d4f30](https://github.com/user-attachments/assets/4d68ed82-b4c2-4703-aa01-b3ef5c930304)

**Comment by Loukious** [comment]
> I have the problem that when I start the key generator script, the system detects that it has a corrupt file or virus that prevents it from functioning correctly. A few hours ago, I was testing it and it worked, plus I did multistream. This surprises me. Is there any solution? This problem appeared on the date and time of this post. I would greatly appreciate your help. ![Imagen de WhatsApp 2024-08-18 a las 15 30 57_be8d4f30](https://private-user-images.githubusercontent.com/178741623/358937409-4d68ed82-b4c2-4703-aa01-b3ef5c930304.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMTc4OTcsIm5iZiI6MTcyNDAxNzU5NywicGF0aCI6Ii8xNzg3NDE2MjMvMzU4OTM3NDA5LTRkNjhlZDgyLWI0YzItNDcwMy1hYTAxLWIzZWY1YzkzMDMwNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQyMTQ2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGU2NmE0ODVkNDIyMzI4NWQ1OTFlNmFhYjllMTBmNzE5ZTAzZmY1OTk1YzQ1NDAzOGFiYTYxNDkwNDFhMDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dbT6qAhor2IzP1z4fCP0IiXvGi3nckK_Wm18B3EitDw)

Add the file to windows defender [exclusion](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26).

**Comment by JulioGomez11** [comment]
I was thinking of adding an exception to the antivirus, but I started analyzing the executable, and the analysis shows me 27 threats like trojans. I’m not sure how safe it is to add it just like that. Won’t you do a review of it?

**Comment by Loukious** [comment]
> I was thinking of adding an exception to the antivirus, but I started analyzing the executable, and the analysis shows me 27 threats like trojans.
False positive.
> I’m not sure how safe it is to add it just like that.
The project is open source, feel free to go through it line by line. It's also compiled on the github servers through [github actions](https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/actions/runs/10356237364) so I'm not uploading the files manually.
> Won’t you do a review of it?
What kind of review exactly?
