### ISSUE TITLE
Program says I'm live but it does not show on other devices or private browsers. 

### ISSUE THREAD

**Issue by C1Platinum316** [Loukious/StreamLabsTikTokStreamKeyGenerator#15]
I tried using this tool earlier today. I have been approved for TikTok to steam via Streamlabs OBS. I followed the steps to extract the server url and stream key. Whenever I try to go live via Aitium vertical canvas, it shows I'm live but it does not appear I'm live when viewing my tiktok profile from other devices or private browsers.

**Comment by Loukious** [comment]
Should probably ask Streamlabs themselves about this. This tool only utilize their API.

**Comment by C1Platinum316** [comment]
> Should probably ask Streamlabs themselves about this. This tool only utilize their API.

Do I need to keep Streamlabs OBS open in the background when trying to stream from OBS Studio?

**Comment by Loukious** [comment]
> > Should probably ask Streamlabs themselves about this. This tool only utilize their API.
> 
> Do I need to keep Streamlabs OBS open in the background when trying to stream from OBS Studio?

No, you don't need Streamlabs. I'm saying if you're having issues during a stream it's on Streamlabs end not my app. My app only provides you with the stream key.
