### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by javierFuentesDev** [Loukious/StreamLabsTikTokStreamKeyGenerator#18]
![image](https://github.com/user-attachments/assets/cf4b26d9-45c4-48c9-94b7-52f5ae90dae3)

**Comment by Loukious** [comment]
Can you paste the whole logs here and tell me when the error happens?

**Comment by javierFuentesDev** [comment]
![image](https://github.com/user-attachments/assets/fc58bb77-69cb-45a1-ab68-1b74945be432)
This is all the info I have.
The error happened when I opened the .exe. I have installed Streamlabs and I'm logged in with TikTok. I also have TikTok streaming permissions.

**Comment by Loukious** [comment]
> ![image](https://private-user-images.githubusercontent.com/104512290/360043877-fc58bb77-69cb-45a1-ab68-1b74945be432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjk0NzMsIm5iZiI6MTcyNDM2OTE3MywicGF0aCI6Ii8xMDQ1MTIyOTAvMzYwMDQzODc3LWZjNThiYjc3LTY5Y2ItNDVhMS1hYjY4LTFiNzQ5NDViZTQzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQyMzI2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGI3MWVlZmU2MWQwYjAyN2ZlMWEyNjFhNGQxNTZjODgxNjk4NDgzMzJhNjY2YWZhNDVkNDc4OTc2OWFjMjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OUY1oi25yWtJngIRj9fss7ZbmtcRjAs9L-thstu66yY) This is all the info I have. The error happened when I opened the .exe. I have installed Streamlabs and I'm logged in with TikTok. I also have TikTok streaming permissions.

Try the latest version.

**Comment by javierFuentesDev** [comment]
Problem solved, great work men, Thanks U
