### ISSUE TITLE
Running into this every time 

### ISSUE THREAD

**Issue by ItzzFocus** [Loukious/StreamLabsTikTokStreamKeyGenerator#19]
![b9cabe1457c8c66885160408147e2ac2](https://github.com/user-attachments/assets/13fd7118-6a90-4369-b2cf-861dd927263d)
Does anyone know how I can fix this

**Comment by Loukious** [comment]
Keep trying a couple of times. If it didn't work, just install StreamLabs and login to get the token.

**Comment by ItzzFocus** [comment]
got it to work thank you!
