### ISSUE TITLE
Error on MacOS ARM

### ISSUE THREAD

**Issue by StaAnaDistrict** [Loukious/StreamLabsTikTokStreamKeyGenerator#20]
Keep getting this error when opening the extracted file:

> You can’t open the application “StreamLabsTikTokStreamKeyGeneratorDebug-arm64” because it may be damaged or incomplete.

**Comment by Loukious** [comment]
> Keep getting this error when opening the extracted file:
> 
> > You can’t open the application “StreamLabsTikTokStreamKeyGeneratorDebug-arm64” because it may be damaged or incomplete.

Yeah I can't help with that I already gave up on MacOS. I don't have the device to test on it.

**Comment by StaAnaDistrict** [comment]
It's okay man, I really appreciate this community and people like you who continuously contribute here. Still hopeful that it'd work in the future. Thanks for your effort!

**Comment by Loukious** [comment]
> It's okay man, I really appreciate this community and people like you who continuously contribute here. Still hopeful that it'd work in the future. Thanks for your effort!

You can download Python, clone this repo, install requirements then run the script and it will work fine BTW. Only the bundled app is broken.

**Comment by StaAnaDistrict** [comment]
Yeah, I can confirm that it does work when its done using the terminal and using python3. Thanks for that man!

**Comment by StaAnaDistrict** [comment]
The script does open the StreamLabsTikTokStreamKeyGenerator.py via terminal but when the Go Live button is clicked, it does pop-up with an error. Another thing I noticed is that when I run the StreamLabsTikTokStreamKeyGenerator.py, the terminal does say Error Loading Config. All the repo has been cloned through python.

**Comment by Loukious** [comment]
> The script does open the StreamLabsTikTokStreamKeyGenerator.py via terminal but when the Go Live button is clicked, it does pop-up with an error. Another thing I noticed is that when I run the StreamLabsTikTokStreamKeyGenerator.py, the terminal does say Error Loading Config. All the repo has been cloned through python.

You have to post logs/error message. The "Error Loading Config" is normal.
