### ISSUE TITLE
ARM64 - Damaged or incomplete

### ISSUE THREAD

**Issue by jenjoy3724** [Loukious/StreamLabsTikTokStreamKeyGenerator#21]
Hello,

I have this issue
![Screenshot 2024-08-24 at 16 19 10](https://github.com/user-attachments/assets/83accb3a-11a2-451e-9d29-47b12aef6b82)
Same with both Release and Debug

**Comment by Loukious** [comment]
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/issues/20
