### ISSUE TITLE
Mac version ☺️

### ISSUE THREAD

**Issue by animalxshadow** [Loukious/StreamLabsTikTokStreamKeyGenerator#23]
Hi ! I’m pretty sure u’re working on it but I’ve to tell you that Mac version not working . I’ve forbidden sign on the app can’t lauch it ( M1 Max ) , maybe I’m doing something wrong .

thank for your time can’t wait to try it 👌🏾

**Comment by Loukious** [comment]
For the mac version I really can't make sure it compatible will of them. I don't own a mac so it's really hard to test it. But to use the app you can download Python, install the requirements and run the script, it should work fine.
