### ISSUE TITLE
error going live

### ISSUE THREAD

**Issue by vampsk1** [Loukious/StreamLabsTikTokStreamKeyGenerator#25]
when i open it shows "error loading config file" along with the generator. also i think its stuck logged in to my other account without live access 
![Screenshot (1)](https://github.com/user-attachments/assets/42826444-5f0d-47dc-a8ed-430a3a5c4d8f)

**Comment by Loukious** [comment]
> when i open it shows "error loading config file" along with the generator.

Ignore it. Once you save config, it will be gone.

> also i think its stuck logged in to my other account without live access

Then change your account?

**Comment by Loukious** [comment]
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/latest
Latest version should show which account you're currently logged into.
