### ISSUE TITLE
doesn't open on intel mac

### ISSUE THREAD

**Issue by aubreydigital** [Loukious/StreamLabsTikTokStreamKeyGenerator#29]
<img width="247" alt="Screenshot 2024-09-04 at 10 18 49 AM" src="https://github.com/user-attachments/assets/f071c0df-54c9-4ac1-9655-371bfe4b1e02">

**Comment by Loukious** [comment]
https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/issues/20
