### ISSUE TITLE
The generator was working for me but....

### ISSUE THREAD

**Issue by SPIDEYAHGAMER** [Loukious/StreamLabsTikTokStreamKeyGenerator#3]
Hello fellow coder here i was going through your files to see if there was any way to get access to the debugger i am running it on my PC and even downloaded the source files to see if it was missing files from the source code the debugger doesn't automatically run debugging protocols on the program and source file. i tried to run the debugger and even see if i could do a manual debug and it didn't work. now i am trying to go live on my tiktok account and its saying i am having an error. if any help at all it would be much appreciated. Thank you!

![image_2024-07-28_173357709](https://github.com/user-attachments/assets/d44a21bd-aeec-41da-805e-57149932c64d)

**Comment by SPIDEYAHGAMER** [comment]
i had originally did it how it was intended to be run with streamlabs and with logging in to streamlabs and it worked but it has since stopped working?!?!?

**Comment by ther3y3s** [comment]
Yeah same problem for me too

**Comment by Loukious** [comment]
Do you have access to streamlab tiktok live?

**Comment by ther3y3s** [comment]
yea, i used this tool yesterday too

**Comment by Loukious** [comment]
Streamlabs related issue.
![image](https://github.com/user-attachments/assets/e7e4e04c-4019-49c0-9119-c5333f110f8c)

**Comment by SPIDEYAHGAMER** [comment]
oh TY didnt see this post!
