### ISSUE TITLE
Error Saving Config

### ISSUE THREAD

**Issue by D4wny3l** [Loukious/StreamLabsTikTokStreamKeyGenerator#30]
Whenever I try to "Save Config" I get this error " PermissionError: [Errno 13] Permission denied: 'config.json' "

![image](https://github.com/user-attachments/assets/a7f448d4-7f18-4cde-a64a-6720cbca8ed4)

**Comment by Loukious** [comment]
What platform you're running the app on? Windows?

**Comment by D4wny3l** [comment]
Yeah, Windows 10

**Comment by Loukious** [comment]
> Yeah, Windows 10

Try placing the app somewhere else where all apps/users have permissions to create files. Example: inside a folder in the desktop or downloads folder etc..

**Comment by D4wny3l** [comment]
It wa already in downloads folder, but I moved to desktop to test and I don't get the original error (yay!) but I'm still unable to go live and get this pop up whenever I click "Go Live" after Saving Config. I also only have the option to select "Other" under game which isn't a huge deal, but I'm just trying to provide as much information as possible. Thank you for being so helpful through this!! 

![image](https://github.com/user-attachments/assets/c5d0b379-f3ff-484f-b2e8-4f4c3c996c66)

**Comment by Loukious** [comment]
> It wa already in downloads folder, but I moved to desktop to test and I don't get the original error (yay!) but I'm still unable to go live and get this pop up whenever I click "Go Live" after Saving Config. I also only have the option to select "Other" under game which isn't a huge deal, but I'm just trying to provide as much information as possible. Thank you for being so helpful through this!!
> 
> ![image](https://private-user-images.githubusercontent.com/180589047/366069009-c5d0b379-f3ff-484f-b2e8-4f4c3c996c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODYzMzEsIm5iZiI6MTcyNTk4NjAzMSwicGF0aCI6Ii8xODA1ODkwNDcvMzY2MDY5MDA5LWM1ZDBiMzc5LWYzZmYtNDg0Zi1iMmU4LTRmNGMzYzk5NmM2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNjMzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGZlYTNiYjUyNGJjNTA2MWU5MDg2Y2NmNWVhZDIxMGIyZjJkZWFlNDRhZTE1ZjA4NDk1YmE5YTdmNzFhNTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AHZ-1DvmRfSonNQVNWHW6rySvP8IGu37zaSu4iCREpA)

Seems to be an issue with your account. Can you try using streamlabs with that same account and see if you can go live?

**Comment by D4wny3l** [comment]
I just confirmed I could go live on TT using just streamlabs
