### ISSUE TITLE
I can't go live

### ISSUE THREAD

**Issue by xonvnt** [Loukious/StreamLabsTikTokStreamKeyGenerator#31]
I already have the token ready but once i press go live this happens 
![image](https://github.com/user-attachments/assets/57ec7866-1abd-4636-8487-def80abf3b5f)

**Comment by sfxworks** [comment]
Not sure if this is new, but the stream urls I am given do not work at all. When I try to manually ping them, I cant reach them.

```
 sam  ping push-rtmp-f5-tt01.tiktokcdn-us.com
PING push-fcdn-ttp3.s.worldfcdn2.com (71.18.9.245) 56(84) bytes of data.
From 71.18.9.33 icmp_seq=1 Time to live exceeded
From 71.18.9.33 icmp_seq=2 Time to live exceeded
From 71.18.9.33 icmp_seq=3 Time to live exceeded
^C
--- push-fcdn-ttp3.s.worldfcdn2.com ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2003ms

 sam  curl https://push-rtmp-f5-tt01.tiktokcdn-us.com:443
^C
 sam  ping push-rtmp-f5-tt01.tiktokcdn-us.com
PING push-fcdn-ttp1.s.worldfcdn2.com (147.160.177.42) 56(84) bytes of data.
^C
--- push-fcdn-ttp1.s.worldfcdn2.com ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6081ms
```


I put the stream url and keys in OBS. Still can't reach it.

**Comment by Loukious** [comment]
> Not sure if this is new, but the stream urls I am given do not work at all. When I try to manually ping them, I cant reach them.
> 
> ```
>  sam  ping push-rtmp-f5-tt01.tiktokcdn-us.com
> PING push-fcdn-ttp3.s.worldfcdn2.com (71.18.9.245) 56(84) bytes of data.
> From 71.18.9.33 icmp_seq=1 Time to live exceeded
> From 71.18.9.33 icmp_seq=2 Time to live exceeded
> From 71.18.9.33 icmp_seq=3 Time to live exceeded
> ^C
> --- push-fcdn-ttp3.s.worldfcdn2.com ping statistics ---
> 3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2003ms
> 
>  sam  curl https://push-rtmp-f5-tt01.tiktokcdn-us.com:443
> ^C
>  sam  ping push-rtmp-f5-tt01.tiktokcdn-us.com
> PING push-fcdn-ttp1.s.worldfcdn2.com (147.160.177.42) 56(84) bytes of data.
> ^C
> --- push-fcdn-ttp1.s.worldfcdn2.com ping statistics ---
> 7 packets transmitted, 0 received, 100% packet loss, time 6081ms
> ```
> 
> I put the stream url and keys in OBS. Still can't reach it.

Try streaming using StreamLabs.

**Comment by sfxworks** [comment]
Streamlabs works just fine, but I had to switch my whole OS to windows instead of Linux to get it working is what I was trying to avoid. Would much rather this work.

**Comment by Loukious** [comment]
> Streamlabs works just fine, but I had to switch my whole OS to windows instead of Linux to get it working is what I was trying to avoid. Would much rather this work.

If it's generating a key, the Generator's job is done successfully. The connection issues are 100% on your end whether it's OBS or some firewall issue and definitely not my app because it's just a wrapper for the StreamLabs API.

**Comment by sfxworks** [comment]
It's as if the key doesn't work with the provided server.  I haven't looked into how streamlabs does it, but the key is not valid for the given rtmp server. Either that or I'm not putting it correctly into obs. 

It might also be possible TikTok servers just don't respond to ICMP, which would make me previous comment irrelevant.

**Comment by Loukious** [comment]
> It's as if the key doesn't work with the provided server. I haven't looked into how streamlabs does it, but the key is not valid for the given rtmp server. Either that or I'm not putting it correctly into obs.
> 
> It might also be possible TikTok servers just don't respond to ICMP, which would make me previous comment irrelevant.

It's definitely something on your end blocking the connection. I can ping the server just fine
![image](https://github.com/user-attachments/assets/1959b28a-7886-43b3-9f9f-ab0b127042ba)
