### ISSUE TITLE
Vertical url and token 

### ISSUE THREAD

**Issue by Drilmo** [Loukious/StreamLabsTikTokStreamKeyGenerator#33]
### Description

Do you think it's possible to add vertical url and token ? To send both vertical and horizontal streams, the aim being to have both a vertical and a horizontal view (like tiktok live studio).

### Reproduction steps

```bash
--
```

### OS

Windows, Linux, Mac

**Comment by Loukious** [comment]
I'm not sure. Is that feature available in StreamLabs?

**Comment by Drilmo** [comment]
i'm so sad i don't feel like it's there
