### ISSUE TITLE
🐛 [BUG] - "I think this is not a bug" - Type of content live

### ISSUE THREAD

**Issue by RSAKing** [Loukious/StreamLabsTikTokStreamKeyGenerator#34]
### Description

Hey man, 
First, I hope you are well!
Second, I would like to know if is possible to add in your app the option/flag to sinalize about the live content, if this content is for adult or not. In my cause, usually do a live playing games where had violence or similar, on this way Tik Tok reduce my reach in the app.

Finally, thanks a lot for this wondefull and functionable aplication!

bye!

![image](https://github.com/user-attachments/assets/20117357-89ae-4871-895b-ac8b8bba01d5)
![image](https://github.com/user-attachments/assets/4df073ef-f5b5-43f9-bbaa-56c270069a7f)

^How it was in your past version app. (see the attach)

### Reproduction steps

```bash
I think we don't need this lol
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Not applicable
```

### OS

Windows

**Comment by Loukious** [comment]
It's not possible. StreamLabs limitation. You can try submitting a request to them directly [here](https://support.streamlabs.com/hc/en-us/requests/new) to add it as a feature.

**Comment by Loukious** [comment]
It seems like StreamLabs has added this feature. I've added it to my app as well in the new version https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.2
