### ISSUE TITLE
🐛 [BUG] - Error when open on windows

### ISSUE THREAD

**Issue by renzo01** [Loukious/StreamLabsTikTokStreamKeyGenerator#35]
### Description

The windows defender detects it as virus, please fix that
![image](https://github.com/user-attachments/assets/b7815104-26cd-42b6-8cab-4bca69673e4e)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Can't be fixed. Use action > restore.
