### ISSUE TITLE
🐛 [BUG] - <Error starting stream>

### ISSUE THREAD

**Issue by syaa24** [Loukious/StreamLabsTikTokStreamKeyGenerator#39]
### Description

I have followed the steps, but when I press live now a message appears that failed to broadcast live, and there is a message like the one in the picture, please help me Mr. loukious so I can go live on my tiktok. My name is Syaa from Indonesia, thank you.

![eror 1](https://github.com/user-attachments/assets/2dfe4731-2c66-494f-b28b-251b6a2fb3d4)
![Error](https://github.com/user-attachments/assets/0bbcc94b-35bf-48e9-b941-6af2cb323afe)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Windows

**Comment by Loukious** [comment]
It says you never applied to get Streamlabs live access.
