### ISSUE TITLE
non-gaming streams

### ISSUE THREAD

**Issue by vexhani** [Loukious/StreamLabsTikTokStreamKeyGenerator#4]
hey there. is there any way to toggle a different stream category other than gaming? trying to stream some songwriting / live rehearsals using obs/audio interface. thanks!

**Comment by Loukious** [comment]
You can try submitting a feature request [here](https://support.streamlabs.com/hc/en-us/requests/new?ticket_form_id=1260806623850) to Streamlabs directly. If they add that feature, I can definitely add it here as well. Currently Streamlabs doesn't offer such thing. The only way to do it probably is:
1.  Start live using Streamlabs API.
2. Use TikTok api to change Stream category. 
Which is tbh a lot of work for so little benefit.
