### ISSUE TITLE
🐛 [BUG] - ModuleNotFoundError: No module named 'tkinter' when running Linux binary

### ISSUE THREAD

**Issue by narnacle** [Loukious/StreamLabsTikTokStreamKeyGenerator#40]
### Description

I encountered a `ModuleNotFoundError: No module named 'tkinter'` error when attempting to run the Linux binary `StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin` on my system. Despite having `tkinter` installed for Python 3, the binary fails to locate the module, suggesting it might not be properly bundled or detected by the executable.

### Reproduction steps

1. Download `StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin` on a 64-bit Linux system.
2. Make the binary executable:
   
   ```bash
   chmod +x ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
   
3. Run the binary:
   ```bash
   ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
   ```
4. Observe the following error:
   ```
   Traceback (most recent call last):
     File "/tmp/onefile_xxxx_xxxxxxxxx/StreamLabsTikTokStreamKeyGenerator.py", line 4, in <module>
   ModuleNotFoundError: No module named 'tkinter'
   ```

**Expected Behavior:**
The program should launch successfully without encountering the `tkinter` module error, as `tkinter` is already installed on the system.

**Observed Behavior:**
The program crashes with a `ModuleNotFoundError`, indicating that it cannot find the `tkinter` module, despite `python3-tk` being installed.

**System Information:**
- **OS:** Ubuntu 22.04 (64-bit)
- **Kernel:** 6.8.0-41-generic
- **Architecture:** x86_64
- **Python Version:** Python 3.12.3 (with `tkinter` installed and functional)
- **Binary Version:** `StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin`
- **File System Info:**
  - Binary is correctly identified as an `ELF 64-bit` executable for GNU/Linux 3.2.0
  - Output of `ldd ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin` shows no missing shared libraries.
  - Sufficient disk space and permissions on `/tmp` (Used: 108G/468G).

**Troubleshooting Steps Taken:**
1. Verified that `python3-tk` is installed and functional on the system:
   ```bash
   python3 -c "import tkinter; print('tkinter is installed')"
   ```
   Output: `tkinter is installed`
   
2. Checked if the binary is compatible with the system architecture:
   ```bash
   file ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
   ```
   Output confirms it's a 64-bit executable compatible with my system.

3. Verified no missing shared libraries using:
   ```bash
   ldd ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
   ```
   No missing dependencies were reported.

4. Attempted to set the `PYTHONPATH` explicitly to point to the correct Python version:
   ```bash
   export PYTHONPATH=/usr/lib/python3.12
   sudo ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
   ```
   Issue persisted.

5. Checked if the binary had any references to Python versions or modules using:
   ```bash
   strings ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin | grep python
   ```
   No Python-related strings were found, suggesting the binary may be using its own bundled environment.

6. Verified sufficient permissions and space for `/tmp`:
   ```bash
   df -h /tmp
   ls -ld /tmp
   ```
   No issues were found with permissions or disk space.

**Additional Information:**
- The error occurs inside a temporary directory (`/tmp/onefile_xxxxx`), indicating that the binary might be unpacking files there. The `tkinter` module seems to be missing from this temporary package or environment.
- It is unclear which Python interpreter the binary is using, as there are no explicit references within the binary to Python when using `strings`.

**Possible Cause:**
The binary might not be correctly bundling or referencing the system’s Python installation for accessing `tkinter`. It’s possible that the packaging tool (e.g., `PyInstaller` or `cx_Freeze`) did not include the `tkinter` module when building the executable.

**Suggested Fix:**
- Ensure that `tkinter` is included in the build process for the Linux version of the binary.
- If using `PyInstaller`, you can include `tkinter` as a hidden import:
  ```bash
  pyinstaller --hidden-import=tkinter your_script.py
  ```
- Alternatively, ensure that the binary is correctly linked to the system’s Python environment if the intention is to use the system Python.

### Logs

- Output of file ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
```bash
./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=dda0f96dae62e374814f7fc50b6f753fb784e7e7, for GNU/Linux 3.2.0, stripped
```
- Output of ldd ./StreamLabsTikTokStreamKeyGeneratorRelease-linux.bin
```bash
	linux-vdso.so.1 (0x00007ffd2cb85000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2935c00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2935fb9000)
```
- Output of strace command if required
`ModuleNotFoundError: No module named 'tkinter'`

### OS

Linux

**Comment by Loukious** [comment]
Can you try this version? https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.0

**Comment by narnacle** [comment]
The new error suggests that the tkinter plugin was not enabled during the compilation process using Nuitka.

`Nuitka: Need to use '--enable-plugin=tk-inter' option during compilation for tk-inter to work!`

**Comment by Loukious** [comment]
> The new error suggests that the tkinter plugin was not enabled during the compilation process using Nuitka.
> 
> `Nuitka: Need to use '--enable-plugin=tk-inter' option during compilation for tk-inter to work!`

I thought I had it enabled. Try now. Same version https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.0
