### ISSUE TITLE
🐛 [BUG] - tiktok Heartbeat

### ISSUE THREAD

**Issue by haig233** [Loukious/StreamLabsTikTokStreamKeyGenerator#41]
### Description

As far as I know, when Tiktok is live streaming on the APP, it will periodically send a Heartbeat to the TikTok server to detect your live streaming status, and will also respond with some information to tell the client what the server has returned. If the Heartbeat is missing, your live streaming may be forcibly stopped by TikTok, or even the live streaming permission may be suspended. However, when using OBS for live streaming, it will not come with this information, nor will it send a Heartbeat. Is it possible to run the program while OBS is streaming, and then the program can imitate TikTok's Heartbeat?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
It doesn't have anything to do with how TikTok works. My app uses the StreamLabs API and their backend should be the one responsible of everything TikTok related.

**Comment by haig233** [comment]
> It doesn't have anything to do with how TikTok works. My app uses the StreamLabs API and their backend should be the one responsible of everything TikTok related.

Is there any other way to contact you? I would like to customize some special functions with you.

**Comment by Loukious** [comment]
> > It doesn't have anything to do with how TikTok works. My app uses the StreamLabs API and their backend should be the one responsible of everything TikTok related.
> 
> Is there any other way to contact you? I would like to customize some special functions with you.

Discord "Loukios" or [linkedin](https://www.linkedin.com/in/wael-hasnaoui/)

**Comment by haig233** [comment]
> Loukios

Friend request sent
