### ISSUE TITLE
🐛 [BUG] - <Bad Category on TikTok>

### ISSUE THREAD

**Issue by luisgs91** [Loukious/StreamLabsTikTokStreamKeyGenerator#42]
### Description

Hi! I am streaming daily a Piano Live Session and everybody tell me that is in wrong category. It shows in gaming and I need it to be music. Can you make it switchable? Because with the other account that I stream gaming is ok because you choose the game, but not for making music. Thank you very much, this app is LIFE SAVING

### Reproduction steps

```bash
1. Go to 'App'
2. Click on 'Go Live'
3. Copy Stream Key on Prism
4. Chooses wrong category
```

### OS

Mac

**Comment by Loukious** [comment]
You can use "other". The limitation isn't on my app's end but on StreamLabs'. You can request the feature to be add on their website [here](https://support.streamlabs.com/hc/en-us/requests/new).

**Comment by luisgs91** [comment]
thanks, I wrote them. If I choose other I believe it will be still in gaming but the game will be other from the ones on the list. Hope they fix it, I will tell you their answer. That's the last piece needed

**Comment by pawKer** [comment]
Hi @Loukious, have there been any updates on this from Streamlabs? Is there a way to manually change the category after going live if not?

**Comment by Loukious** [comment]
> Hi [@Loukious](https://github.com/Loukious), have there been any updates on this from Streamlabs? Is there a way to manually change the category after going live if not?

Yes. If you click "Open Live Monitor" in my app it will redirect you to a website where you can change the category.
