### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by inkicthus** [Loukious/StreamLabsTikTokStreamKeyGenerator#5]
I absolutely loved old TikTokStreamkeyGenerator and I've used it consistently for months, but I saw that project discontinued in favor of this one. So I setup a Streamlabs account, got my access approved, and installed/connected Streamlabs desktop. I verified that I can go live on TikTok via Streamlabs, but when I try to get the key, the Python script acts like I'm not connected.

<img width="1233" alt="Screenshot 2024-08-06 at 8 56 16 AM" src="https://github.com/user-attachments/assets/38ef69ac-bd98-40b4-9785-424cb7c519b9">

<img width="258" alt="Screenshot 2024-08-06 at 8 56 32 AM" src="https://github.com/user-attachments/assets/0a6db52c-f02f-4075-96d9-2949eff80315">

What am I missing here?

**Comment by Loukious** [comment]
I'm aware that it's not working on Mac. If you want to help me add support to it, contact me on discord (loukios). It just needs few adjustments to find the location of the logs file in Mac and I don't own one so I have no clue where it is.

**Comment by felipegmg** [comment]
How do I run it on MacOS? Thnks!

**Comment by inkicthus** [comment]
Working!
<img width="982" alt="Screenshot 2024-08-08 at 4 28 35 PM" src="https://github.com/user-attachments/assets/88ffb4a8-d567-41a5-984b-3a4b2513e819">

Is there any way around the Game part? My streams are not games. In the old version, I didn't need that. Now it looks like I'm forced to just pick some game at random in order to go live. Is that correct?

**Comment by inkicthus** [comment]
In Streamlabs Desktop, there is an "Other" option
<img width="911" alt="Screenshot 2024-08-08 at 4 37 19 PM" src="https://github.com/user-attachments/assets/892dd217-344d-4143-92b8-6ab1c0d1d9d7">

I tried to figure out how to implement that, but I'm a C# developer, not Python, so I'm out of my element here

**Comment by inkicthus** [comment]
Tested and working on Mac. The Game question is separate.

**Comment by Loukious** [comment]
> In Streamlabs Desktop, there is an "Other" option <img alt="Screenshot 2024-08-08 at 4 37 19 PM" width="911" src="https://private-user-images.githubusercontent.com/19429716/356379084-892dd217-344d-4143-92b8-6ab1c0d1d9d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTcxMDIsIm5iZiI6MTcyMzE1NjgwMiwicGF0aCI6Ii8xOTQyOTcxNi8zNTYzNzkwODQtODkyZGQyMTctMzQ0ZC00MTQzLTkyYjgtNmFiMWMwZDFkOWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIyNDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YTFhZmMxNjIyNzc1OTYyNzNkMjM0MjQyNDc1OGI2MjVhM2M2ZTQyY2FhN2VkNWZiNTE5MDgwYTcxMjhiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Poxe_PzE3YXBqxcVs1-7LoDfnfGr-TKv12CkJkfYlTg">
> 
> I tried to figure out how to implement that, but I'm a C# developer, not Python, so I'm out of my element here

https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v0.0.4
Added on the latest version

**Comment by inkicthus** [comment]
Tested and working. A little confusing that there is no "Other" option in the dropdown, but I can leave it empty and it comes through as Other, so that's good enough for me. Thanks!
