### ISSUE TITLE
🐛 [BUG] - Trojan detected

### ISSUE THREAD

**Issue by castrordg** [Loukious/StreamLabsTikTokStreamKeyGenerator#52]
### Description

Both my windows and my browser detected a trojan virus on the download file for the key generator :/

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Use search before you create an issue.

**Comment by Loukious** [comment]
Try the latest version here https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.3
