### ISSUE TITLE
🐛 [BUG] Virus !

### ISSUE THREAD

**Issue by BrazucaNY** [Loukious/StreamLabsTikTokStreamKeyGenerator#54]
### Description

![Screenshot 2024-12-02 000342](https://github.com/user-attachments/assets/0c0bdb63-00e2-4354-af7a-38739b9299dd)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Use search before you open an issue.
