### ISSUE TITLE
🐛 [BUG] - "Chrome blocked this download because the file is dangerous" 

### ISSUE THREAD

**Issue by joshistoast** [Loukious/StreamLabsTikTokStreamKeyGenerator#55]
### Description

I know I can simply go into download history and manually resume the download, but chrome telling me this is assuredly malware spooks me.

![image](https://github.com/user-attachments/assets/670911d8-de00-41c7-82c7-753f1cb3ab35)
![image](https://github.com/user-attachments/assets/5417d0c5-ef29-45d0-b071-ed414d53597c)

### Reproduction steps

```bash
1. Open 'Google Chrome'
1. Go to 'Release'
2. Click on '1.0.2'
3. Download 'StreamLabsTikTokStreamKeyGeneratorRelease-win.zip'
4. See error
```

### OS

Windows

**Comment by Loukious** [comment]
Use search before you open an issue.

**Comment by Loukious** [comment]
Try the latest version here https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.3
