### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by KvngAdro** [Loukious/StreamLabsTikTokStreamKeyGenerator#56]
### Description

New To Using All Of This Stuff But Wont Let Me Open It.
![Screenshot 2024-12-07 001319](https://github.com/user-attachments/assets/cb218eb9-81c8-4afa-a6ec-5d3e10a1cb75)
![Screenshot 2024-12-07 001314](https://github.com/user-attachments/assets/8918e08c-3f2f-409e-a5fb-8dd01797befb)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Search how to add a file to windows defender exclusion list.

**Comment by KvngAdro** [comment]
Much Appreciated!
