### ISSUE TITLE
🐛 [BUG] - <title>Virus Detected

### ISSUE THREAD

**Issue by ti0cl** [Loukious/StreamLabsTikTokStreamKeyGenerator#58]
### Description

Virus detected during download, using Google Chrome or any other browser. I don't use antivirus and Windows Defender is not active. Even so, the file is not downloaded.

Vírus detectado durante o download, usando o google chrome ou qualquer outro navegador. Não uso antivírus e o Windows Defender não está ativo. Mesmo assim o arquivo não é baixado.

![Sem título 1](https://github.com/user-attachments/assets/068a5341-f623-4071-862f-e4a9982c1ea4)

### Reproduction steps

```bash
Virus detected during download, using Google Chrome or any other browser. I don't use antivirus and Windows Defender is not active. Even so, the file is not downloaded.

Vírus detectado durante o download, usando o google chrome ou qualquer outro navegador. Não uso antivírus e o Windows Defender não está ativo. Mesmo assim o arquivo não é baixado.
```

### Screenshots

```bash
![Sem título 1](https://github.com/user-attachments/assets/068a5341-f623-4071-862f-e4a9982c1ea4)
```

### OS

Windows

**Comment by Loukious** [comment]
Go to full download history and do this
![image](https://github.com/user-attachments/assets/34a5a57c-87ad-46f9-a9aa-d420fa3dd5b0)

**Comment by ti0cl** [comment]
I already did this and couldn't download it. I even put this in the print. Check it out!
![Sem título 1](https://github.com/user-attachments/assets/46817031-9fc1-4dc6-a7dd-cb0218563208)
