### ISSUE TITLE
I've logged in Tiktok Live but can't find the API token

### ISSUE THREAD

**Issue by Enderwonder** [Loukious/StreamLabsTikTokStreamKeyGenerator#6]
It can't get the API token even I logged in

![image](https://github.com/user-attachments/assets/870faa2f-93e2-4240-a09a-01503a29c93d)
![image](https://github.com/user-attachments/assets/4ddccdec-4257-494d-8e15-44b4ce5c65b2)

**Comment by Loukious** [comment]
Do it like this;
1. Open streamlabs 
2. Close streamlabs (DON'T GO LIVE ON STREAMLABS).
3. Open the app and save the token somewhere for future use.

**Comment by Enderwonder** [comment]
nope, still can't get the token. Just thinking if it's the UTF-8 username problem.

![image](https://github.com/user-attachments/assets/452a9de4-7cf0-47bd-99fb-6338f45befb3)

**Comment by Loukious** [comment]
> nope, still can't get the token. Just thinking if it's the UTF-8 username problem.
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356465947-452a9de4-7cf0-47bd-99fb-6338f45befb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDAxMzIsIm5iZiI6MTcyMzE5OTgzMiwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NDY1OTQ3LTQ1MmE5ZGU0LTdjZjAtNDdiZC05OWZiLTYzMzhmNDViZWZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxMDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjNmZjM1Y2E1ODJmYzI2OWM1ODcwZTA5ZGE0ZmEzODU1ZTcyYjgyZDE4MDg3YWQ3NTViZTk3YTdjYmI0YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1gx_Ya_dwF5VowPivPK9zE8VQB0AUcZXTm134NcAGac)

Are you on Windows? Can you verify that there are files in `%appdata%\slobs-client\Local Storage\leveldb\` ? The app should handle UTF-8 just fine.

**Comment by Loukious** [comment]
@Enderwonder give the new version a try. If the auto loading of the token didn't work, I added a new method to load it through the browser.

**Comment by Enderwonder** [comment]
I'll try the new version now.

There's file there, but I opened it with notepad, and it shown up lots of garbled characters.

![image](https://github.com/user-attachments/assets/4583ddc1-6592-4494-bc80-77f12b567215)

![image](https://github.com/user-attachments/assets/8d12e92b-13aa-48f8-bbce-febaf4967cce)

**Comment by Enderwonder** [comment]
> @Enderwonder give the new version a try. If the auto loading of the token didn't work, I added a new method to load it through the browser.

It pop up these two error message.

![image](https://github.com/user-attachments/assets/94e63fc7-979c-49be-82e5-c8cdc176373e)
![image](https://github.com/user-attachments/assets/47425425-3b6d-447c-8624-577e57190f1b)

**Comment by Loukious** [comment]
> > @Enderwonder give the new version a try. If the auto loading of the token didn't work, I added a new method to load it through the browser.
> 
> It pop up these two error message.
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356712597-94e63fc7-979c-49be-82e5-c8cdc176373e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjg2ODksIm5iZiI6MTcyMzIyODM4OSwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzEyNTk3LTk0ZTYzZmM3LTk3OWMtNDliZS04MmU1LWM4Y2RjMTc2MzczZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxODMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTVjMWM0NTIxOTFkMzc2ODE5MDQ1ZDFhNzAzZmRlNGU4Nzc0NGE4YzdmM2QwYWIyZTc3NzU0Zjc4MjliZTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5IiQCfuu-lZzkk4s9CPJxuThyHUUAzt4IzK4zxq2VQ) ![image](https://private-user-images.githubusercontent.com/177802613/356712655-47425425-3b6d-447c-8624-577e57190f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjg2ODksIm5iZiI6MTcyMzIyODM4OSwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzEyNjU1LTQ3NDI1NDI1LTNiNmQtNDQ3Yy04NjI0LTU3N2U1NzE5MGYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxODMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWE3YjgwMTQwYTBkMGQ0MzM5YjA0Mjc2YjVhMGJhMzNmYmQxYzk2YmM4MGM2NzQ3YmM3N2E2NmViZTExZmVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wtd4dMBIYIxgRe-jEi43rH_-Rj0E8SNEu_WOaiSuZRE)

Are you using the executable or running the Python code directly? If using the executable, can you try running the code directly?

**Comment by Enderwonder** [comment]
> 
> Are you using the executable or running the Python code directly? If using the executable, can you try running the code directly?

I'll try to run the code directly, but i need to download python on my laptop first

**Comment by Enderwonder** [comment]
I run these files directly, I not sure if I'm doing right, but no application pop up.

![image](https://github.com/user-attachments/assets/684bfc36-e784-4f14-be50-a15310294371)

**Comment by Loukious** [comment]
> I run these files directly, I not sure if I'm doing right, but no application pop up.
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356720207-684bfc36-e784-4f14-be50-a15310294371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjk2NTcsIm5iZiI6MTcyMzIyOTM1NywicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzIwMjA3LTY4NGJmYzM2LWU3ODQtNGYxNC1iZTUwLWExNTMxMDI5NDM3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxODQ5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTI5ODQzNTZlNmYwOGMyOTMyMzFkMTIwZWYxMmY1YmJmNTY1N2VlYjM4MWMzMWJjNTFkODI3YTczOTE5YmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QqtxjHUI4adALBNRz5uWCzvLQgFkzc__zcGXhNHZrTI)

Yeah open terminal there and type `python StreamLabsTikTokStreamKeyGenerator.py` or `python3 StreamLabsTikTokStreamKeyGenerator.py`

**Comment by Enderwonder** [comment]
not sure why no respond, or should I gave it admin?

![image](https://github.com/user-attachments/assets/50ffe652-62d2-4465-813f-4bbfb280a583)

**Comment by Enderwonder** [comment]
> 
> Yeah open terminal there and type `python StreamLabsTikTokStreamKeyGenerator.py` or `python3 StreamLabsTikTokStreamKeyGenerator.py`

not sure if it's my python's problem

https://private-user-images.githubusercontent.com/177802613/356721625-50ffe652-62d2-4465-813f-4bbfb280a583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzA1MDEsIm5iZiI6MTcyMzIzMDIwMSwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzIxNjI1LTUwZmZlNjUyLTYyZDItNDQ2NS04MTNmLTRiYmZiMjgwYTU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTAzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGNkMGRhM2M3ZjVkMGMyMGE5NmE4ODVjMTkxMWU1YjE0MDAwOTUyNzgyMTA2ZjdjMDNmOTE4ZTA5ZjlhMmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xRg-OUB1Wfj18PKfxGjSgvon5AcOJBvF52fnObqmR2A

**Comment by Loukious** [comment]
> > Yeah open terminal there and type `python StreamLabsTikTokStreamKeyGenerator.py` or `python3 StreamLabsTikTokStreamKeyGenerator.py`
> 
> not sure if it's my python's problem
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356725187-021cd2fd-ae62-49b9-938a-fb8637d2465f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzA2MzIsIm5iZiI6MTcyMzIzMDMzMiwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzI1MTg3LTAyMWNkMmZkLWFlNjItNDliOS05MzhhLWZiODYzN2QyNDY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDJiMThmOWU2OTQ5MGYyZjc4MzNlMTBjYTQxNzk1NGVhOTg0NTJmZTg4ODVmMjJiMjRhY2Y1ZDFiMGE3M2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uXqU48b2sTn42TDAWneJp-tE2LA5gU8IzfsYJmxNKw0)

Yeah it's not added to path. Can you try this test version and see if it works? https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/download/v0.0.5/StreamLabsTikTokStreamKeyGeneratorTest.exe

**Comment by Enderwonder** [comment]
> > > Yeah open terminal there and type `python StreamLabsTikTokStreamKeyGenerator.py` or `python3 StreamLabsTikTokStreamKeyGenerator.py`
> > 
> > 
> > not sure if it's my python's problem
> > ![image](https://private-user-images.githubusercontent.com/177802613/356725187-021cd2fd-ae62-49b9-938a-fb8637d2465f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzA2MzIsIm5iZiI6MTcyMzIzMDMzMiwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzI1MTg3LTAyMWNkMmZkLWFlNjItNDliOS05MzhhLWZiODYzN2QyNDY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTA1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDJiMThmOWU2OTQ5MGYyZjc4MzNlMTBjYTQxNzk1NGVhOTg0NTJmZTg4ODVmMjJiMjRhY2Y1ZDFiMGE3M2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uXqU48b2sTn42TDAWneJp-tE2LA5gU8IzfsYJmxNKw0)
> 
> Yeah it's not added to path. The issue seem to be because of your windows language. Can you try this test version and see if it works? https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/download/v0.0.5/StreamLabsTikTokStreamKeyGeneratorTest.exe

another error message pop up, but seems like the original problem was solved

![image](https://github.com/user-attachments/assets/2d2d23ff-fadb-43dc-b30a-41e39f38606b)
![image](https://github.com/user-attachments/assets/e892abd9-dff1-42b3-87c5-c0248914ab5b)

**Comment by Loukious** [comment]
> another error message pop up, but seems like the original problem was solved
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356729740-2d2d23ff-fadb-43dc-b30a-41e39f38606b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzE3NTYsIm5iZiI6MTcyMzIzMTQ1NiwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzI5NzQwLTJkMmQyM2ZmLWZhZGItNDNkYy1iMzBhLTQxZTM5ZjM4NjA2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTI0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDc4YTEzODYxYjcwOWFlOTU4OTdhYjZmM2M4YmQ5ZDE3NzEyNThlZTUzOTU0NzMxYjZhNTkwNGNlYmYyZWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yhQKorcGbd4HypurUQdP0LPP96POsTNI4vZoOh0FKUs) ![image](https://private-user-images.githubusercontent.com/177802613/356729804-e892abd9-dff1-42b3-87c5-c0248914ab5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzE3NTYsIm5iZiI6MTcyMzIzMTQ1NiwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzI5ODA0LWU4OTJhYmQ5LWRmZjEtNDJiMy04N2M1LWMwMjQ4OTE0YWI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTI0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzM2ZTZmMmRhZjNiYjYyOTY5NDc1ZDBjZDY0MTc3N2YwYmUxMTJkOWU5NzIyNTQyNzE4NzZlMWE4NzRlZmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pxrBHY3vHf1pAoCLSFM1GkU-cCaEcPdLb_YY2PoTc3I)

Well that confirms my suspicion. Try this https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/download/v0.0.5/StreamLabsTikTokStreamKeyGeneratorTest.exe

**Comment by Enderwonder** [comment]
> 
> Well that confirms my suspicion. Try this https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/download/v0.0.5/StreamLabsTikTokStreamKeyGeneratorTest.exe

wow, that truly installed it without error message, but it failed to load config file?

![image](https://github.com/user-attachments/assets/f5574841-456f-4f8a-924e-e5fc3cdf75ab)

**Comment by Loukious** [comment]
> > Well that confirms my suspicion. Try this [`v0.0.5` StreamLabsTikTokStreamKeyGeneratorTest.exe (download)](https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/download/v0.0.5/StreamLabsTikTokStreamKeyGeneratorTest.exe)
> 
> wow, that truly installed it without error message, but it failed to load config file?
> 
> ![image](https://private-user-images.githubusercontent.com/177802613/356732183-f5574841-456f-4f8a-924e-e5fc3cdf75ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzIzMjksIm5iZiI6MTcyMzIzMjAyOSwicGF0aCI6Ii8xNzc4MDI2MTMvMzU2NzMyMTgzLWY1NTc0ODQxLTQ1NmYtNGY4YS05MjRlLWU1ZmMzY2RmNzVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGNhZDJkMzU4Y2JkYjFhMDlmNzVjOGNlOTMyOTM4MjYwZmY3MDhkNzQzOWNlODdkZmU3NWUyNGQ2ZTM1YTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F8G4TJraXDI8b1BxptD1D1CRGTVmfaqpzAE7AtvofKA)

The config error is normal (because no config was created yet). For the second error if it's causing issues, you can try manually placing the ca.crt in that folder. You can download it [here](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.key). PS: all these issues are caused by your Windows language. An easier solution is to either to install a virtual machine, download the app there and get the token then remove the virtual machine and use the original app on your current Windows by manually putting the token in the config file or use WSL (which is a bit complicated for a beginner). You can also contact me on Discord (Loukios) if you want to continue trying to fix it.
