### ISSUE TITLE
🐛 [BUG] - <Virus?>

### ISSUE THREAD

**Issue by maartents** [Loukious/StreamLabsTikTokStreamKeyGenerator#61]
### Description

WIndowsdefender says its a virus? what s the problem and is someone allready banned by this program?

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Search for older issues before you open a new one.

**Comment by maartents** [comment]
or just give an answer?

**Comment by Loukious** [comment]
Try the latest version here https://github.com/Loukious/StreamLabsTikTokStreamKeyGenerator/releases/tag/v1.0.3
