### ISSUE TITLE
🐛 [BUG] - <Error Starting Stream out of nowhere>

### ISSUE THREAD

**Issue by LaVacaMala23** [Loukious/StreamLabsTikTokStreamKeyGenerator#62]
### Description

I was using this just fine but one day out of nowhere it doesnt let me "Go Live". I verified that I'm not banned from TikTok Live and I still have access, have tried this since I was able to go live with TikTok Live Studio but it wont let me through here. 

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Loukious** [comment]
Can you go live in StreamLabs?

**Comment by CHRiSTARD** [comment]
![Sans titre](https://github.com/user-attachments/assets/0996550c-2053-4b2e-8890-0532928aa34f)

**Comment by CHRiSTARD** [comment]
Hi
I used TiktokStreamKeyGenerator.exe since last week and today i cannot launched (error on screenshot)

I tried with StreamLabsTikTokStreamKeyGenerator (malware ☢) and SLOBS
SLOBS Launched successfully
Impossible to setup StreamLabsTikTokStreamKeyGenerator 

Personnaly, I was creat to use TiktokStreamKeyGenerator.exe before. Why stopped it ?

**Comment by Loukious** [comment]
> ![Sans titre](https://private-user-images.githubusercontent.com/193342336/399494439-0996550c-2053-4b2e-8890-0532928aa34f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzI0NzEsIm5iZiI6MTczNTY3MjE3MSwicGF0aCI6Ii8xOTMzNDIzMzYvMzk5NDk0NDM5LTA5OTY1NTBjLTIwNTMtNGIyZS04ODkwLTA1MzI5MjhhYTM0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxOTA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjQ3MzA3MDFiMTJiMzk2MDRkNDRlYTI1YWZmM2NjMzhjMGE3NzRjMTE2ODA4ZWExNWQ2NjRlNTJlMGYzNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UTcTuO-1Stj2LeietHFzQW9jowj7NzVJBFm-gCmwUyM)

This is for **StreamLabs**TikTokStreamKeyGenerator not the other project. For StreamLabsTikTokStreamKeyGenerator you just add it to windows defender exclusion.
