### ISSUE TITLE
Program opens multiple times on Mac

### ISSUE THREAD

**Issue by abdurahman** [Loukious/StreamLabsTikTokStreamKeyGenerator#7]
The latest version of the program opens up mutliple times on the Mac and it doesnt stop. Here are screenshots showing multiple processes on the Activity Monitor. Also, the browser doesnt open when the dialog box shows that it needs to log into TikTok.

<img width="1512" alt="Screenshot 2024-08-09 at 11 12 48 PM" src="https://github.com/user-attachments/assets/ffab887d-9bc3-462f-95e9-087826f6a31d">

**Comment by Loukious** [comment]
Can you try the debug version in order to show more info in the terminal? Also do you have chrome installed? The app needs Google chrome.

**Comment by abdurahman** [comment]
Sure, i'll do that. I don't have chrome installed though I use Brave Browser

**Comment by Loukious** [comment]
> Sure, i'll do that. I don't have chrome installed though I use Brave Browser. How do I show the terminal?

Use debug version for the terminal.

**Comment by abdurahman** [comment]
Ok. I have opened the debug version but no terminal pops up. How do I show the terminal alongside the app?

**Comment by Loukious** [comment]
You can try the latest version. If it didn't work, then I can't really fix it because I don't have access to any MacOS device to debug it.
