### ISSUE TITLE
"Unhandled exception in script"

### ISSUE THREAD

**Issue by DroogleTV** [Loukious/StreamLabsTikTokStreamKeyGenerator#8]
![Screenshot 2024-08-12 023651](https://github.com/user-attachments/assets/7f3e3e82-9175-48f9-b0e9-7e7ee30cfbe4)

**Comment by Loukious** [comment]
Explain when this error happen.

**Comment by DroogleTV** [comment]
It happens when I attempt to open the .exe most times. If I download a new exe it usually opens fine the first attempt. But then on later attempts it gives that error message.

**Comment by DroogleTV** [comment]
When I open the debug version it seems to open the terminal but then fills with some text and quickly shuts down. Does the log go somewhere I can access?

**Comment by DroogleTV** [comment]
![image](https://github.com/user-attachments/assets/005e1dcf-d03d-4096-bcc0-03c8ca34d910)

Looks like the text inside the debug window is the same as the error message.

**Comment by Loukious** [comment]
> ![image](https://private-user-images.githubusercontent.com/102578590/357081925-005e1dcf-d03d-4096-bcc0-03c8ca34d910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Nzg3OTksIm5iZiI6MTcyMzQ3ODQ5OSwicGF0aCI6Ii8xMDI1Nzg1OTAvMzU3MDgxOTI1LTAwNWUxZGNmLWQwM2QtNDA5Ni1iY2MwLTAzYzhjYTM0ZDkxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxNjAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDk2N2EyZjcxMTg3ZDQwNDQyMjZkYWYwODM1ZTk5MTY5NDU5MjY3ZGI4NWNkYzE3ODQ1OGJlYjQ0MDk0ZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XNDqHwlJIiTx-J3At5JZcStxIpytx-Vsc2hHau4YuA4)
> 
> Looks like the text inside the debug window is the same as the error message.

That crash is most likely happening because of an invalid token.

**Comment by DroogleTV** [comment]
I can't get the app open to load in a new token...

**Comment by DroogleTV** [comment]
OK I think you're right. Deleting the config txt file fixed it. I just won't save config anymore and will load token on each new launch of the app.

**Comment by Loukious** [comment]
> OK I think you're right. Deleting the config txt file fixed it. I just won't save config anymore and will load token on each new launch of the app.

I mean if you successfully loaded the token then saved it, it should not crash on next start up.

**Comment by vampsk1** [comment]
> OK I think you're right. Deleting the config txt file fixed it. I just won't save config anymore and will load token on each new launch of the app.

how did u find the txt file to delete it?

**Comment by DroogleTV** [comment]
It'll be in the same folder you open the .exe from.

**Comment by vampsk1** [comment]
> It'll be in the same folder you open the .exe from.
found it

**Comment by Loukious** [comment]
This should be fixed on latest version.
