### ISSUE TITLE
MacOS version cannot be opened due to damaged or incomplete package

### ISSUE THREAD

**Issue by cyberpapiii** [Loukious/StreamLabsTikTokStreamKeyGenerator#9]
](
![CX  08-12-2024 @ 06 59 22AM](https://github.com/user-attachments/assets/8a723576-3826-467a-936a-0ad8a745408e)

**Comment by Loukious** [comment]
Need someone else to confirm this because there are other MacOS users but they didn't report this issue.

**Comment by Loukious** [comment]
> same here gives the same error on Mac both M1 Chip with OS 12.4 as well as my Intel chip iMac with Os 11

Honestly just download Python, install the requirements and run the script. I have no MacOS device so it's practically impossible for me to test it or debug it.

**Comment by mikemg1989** [comment]
same here

**Comment by Loukious** [comment]
Try one of the latest version if that didn't work, I'm dropping support for MacOS.
